name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        compiler:
        - name: cc
          std: c99
        - name: c++
          std: c++20
        - name: clang
          std: c99
        - name: clang++
          std: c++20
        build:
        - example/nob
        exclude:
        - os: ubuntu-latest
          compiler: { name: clang }
        - os: ubuntu-latest
          compiler: { name: clang++ }
        - os: macos-latest
          compiler: { name: clang }
        - os: macos-latest
          compiler: { name: clang++ }
        - os: windows-latest
          compiler: { name: cc }
        - os: windows-latest
          compiler: { name: c++ }

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: build nob
      shell: bash
      run: ${{ matrix.compiler.name }} -o ${{ matrix.build }} ${{ matrix.build }}.c -std=${{ matrix.compiler.std }} -Wall -Wextra -Wpedantic -g3 -fsanitize=address,undefined
    - name: run nob
      shell: bash
      run: ./${{ matrix.build }}
    - name: run example
      shell: bash
      run: ./example/build/example
