name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    strategy:
      matrix:
        os:
        - name: ubuntu-latest
          compiler: cc
          std: c99
        - name: macos-latest
          compiler: cc
          std: c99
        - name: macos-latest
          compiler: c++
          std: c++20
        - name: windows-latest
          compiler: clang
          std: c99
          env: CC=clang
        - name: windows-latest
          compiler: clang++
          std: c++20
          env: CC=clang
        build:
        - nob

    runs-on: ${{ matrix.os.name }}
    defaults:
      run:
        working-directory: example
    steps:
    - uses: actions/checkout@v4
    - name: build nob
      shell: bash
      run: ${{ matrix.os.compiler }} -o ${{ matrix.build }} ${{ matrix.build }}.c -std=${{ matrix.os.std }} -Wall -Wextra -Wpedantic -g3 -fsanitize=address,undefined
    - name: run nob
      shell: bash
      run: ./${{ matrix.build }}
    - name: run example
      shell: bash
      run: ./build/example
